./img-resize img/objector/01_axon.png img-smalls/objector/01_axon.png
./img-resize img/objector/02_persp.png img-smalls/objector/02_persp.png
./img-resize img/objector/03_pp6.png img-smalls/objector/03_pp6.png
./img-resize img/objector/04_cikl.png img-smalls/objector/04_cikl.png
./img-resize img/objector/c_cube_2b.png img-smalls/objector/c_cube_2b.png
./img-resize img/objector/c_cube_3.png img-smalls/objector/c_cube_3.png
./img-resize img/objector/cessna1.png img-smalls/objector/cessna1.png
./img-resize img/objector/cessna2.png img-smalls/objector/cessna2.png
./img-resize img/objector/cikl_cube.png img-smalls/objector/cikl_cube.png
./img-resize img/objector/cikl_octa.png img-smalls/objector/cikl_octa.png
./img-resize img/objector/cszil5.png img-smalls/objector/cszil5.png
./img-resize img/objector/h01.png img-smalls/objector/h01.png
./img-resize img/objector/h03.png img-smalls/objector/h03.png
./img-resize img/objector/h04.png img-smalls/objector/h04.png
./img-resize img/objector/hdod.png img-smalls/objector/hdod.png
./img-resize img/objector/hdodekaeder.png img-smalls/objector/hdodekaeder.png
./img-resize img/objector/hikozaeder.png img-smalls/objector/hikozaeder.png
./img-resize img/objector/icosa.png img-smalls/objector/icosa.png
./img-resize img/objector/o_dobokocka01.png img-smalls/objector/o_dobokocka01.png
./img-resize img/objector/o_fulleren01.png img-smalls/objector/o_fulleren01.png
./img-resize img/objector/o_kocka01.png img-smalls/objector/o_kocka01.png
./img-resize img/objector/o_kor01.png img-smalls/objector/o_kor01.png
./img-resize img/objector/o_stairs02.png img-smalls/objector/o_stairs02.png
./img-resize img/objector/o_stairs03.png img-smalls/objector/o_stairs03.png
./img-resize img/objector/o_star01.png img-smalls/objector/o_star01.png
./img-resize img/objector/o_star02.png img-smalls/objector/o_star02.png
./img-resize img/objector/pp6_fulleren.gif img-smalls/objector/pp6_fulleren.gif
./img-resize img/objector/pp6_kor2.gif img-smalls/objector/pp6_kor2.gif
./img-resize img/objector/pp6_lepcso.png img-smalls/objector/pp6_lepcso.png
./img-resize img/objector/sq0.png img-smalls/objector/sq0.png
./img-resize img/objector/sq1.png img-smalls/objector/sq1.png
./img-resize img/objector/sq2.png img-smalls/objector/sq2.png
./img-resize img/objector/sq3.png img-smalls/objector/sq3.png
./img-resize img/eq/eq_bit_17.png img-smalls/eq/eq_bit_17.png
./img-resize img/eq/eq_bit_9.png img-smalls/eq/eq_bit_9.png
./img-resize img/eq/eq_bit_si1.png img-smalls/eq/eq_bit_si1.png
./img-resize img/eq/eq_bit_si3.png img-smalls/eq/eq_bit_si3.png
./img-resize img/eq/eq_bit_x.png img-smalls/eq/eq_bit_x.png
./img-resize img/eq/eq_circle_moire.png img-smalls/eq/eq_circle_moire.png
./img-resize img/eq/eq_circle_moire_b.png img-smalls/eq/eq_circle_moire_b.png
./img-resize img/eq/eq_noise_expsin_02d.png img-smalls/eq/eq_noise_expsin_02d.png
./img-resize img/eq/eq_plotter_0001first.png img-smalls/eq/eq_plotter_0001first.png
./img-resize img/eq/eq_plotter_0002second.png img-smalls/eq/eq_plotter_0002second.png
./img-resize img/eq/eq_plotter_02.png img-smalls/eq/eq_plotter_02.png
./img-resize img/eq/eq_plotter_03.png img-smalls/eq/eq_plotter_03.png
./img-resize img/eq/eq_plotter_04.png img-smalls/eq/eq_plotter_04.png
./img-resize img/eq/eq_plotter_05.png img-smalls/eq/eq_plotter_05.png
./img-resize img/eq/eq_plotter_06.png img-smalls/eq/eq_plotter_06.png
./img-resize img/eq/eq_plotter_07.png img-smalls/eq/eq_plotter_07.png
./img-resize img/eq/eq_plotter_comp1.png img-smalls/eq/eq_plotter_comp1.png
./img-resize img/eq/eq_plotter_comp1b.png img-smalls/eq/eq_plotter_comp1b.png
./img-resize img/eq/eq_plotter_comp2.png img-smalls/eq/eq_plotter_comp2.png
./img-resize img/eq/sinquad.png img-smalls/eq/sinquad.png
./img-resize img/eq_frac/J.png img-smalls/eq_frac/J.png
./img-resize img/eq_frac/JE-01.png img-smalls/eq_frac/JE-01.png
./img-resize img/eq_frac/JE-02.png img-smalls/eq_frac/JE-02.png
./img-resize img/eq_frac/JE-03.png img-smalls/eq_frac/JE-03.png
./img-resize img/eq_frac/JE-04.png img-smalls/eq_frac/JE-04.png
./img-resize img/eq_frac/julia.png img-smalls/eq_frac/julia.png
./img-resize img/eq_frac/julia02.png img-smalls/eq_frac/julia02.png
./img-resize img/eq_frac/julia03.png img-smalls/eq_frac/julia03.png
./img-resize img/eq_frac/julia04.png img-smalls/eq_frac/julia04.png
./img-resize img/eq_frac/julia05.png img-smalls/eq_frac/julia05.png
./img-resize img/eq_frac/julia2.png img-smalls/eq_frac/julia2.png
./img-resize img/eq_frac/julia3.png img-smalls/eq_frac/julia3.png
./img-resize img/eq_frac/julia4.png img-smalls/eq_frac/julia4.png
./img-resize img/eq_frac/julia5.png img-smalls/eq_frac/julia5.png
./img-resize img/eq_frac/nr-dot.png img-smalls/eq_frac/nr-dot.png
./img-resize img/eq_frac/nrd01.png img-smalls/eq_frac/nrd01.png
./img-resize img/eq_frac/nrd02.png img-smalls/eq_frac/nrd02.png
./img-resize img/eq_frac/nrd03.png img-smalls/eq_frac/nrd03.png
./img-resize img/eq_frac/nrd04.png img-smalls/eq_frac/nrd04.png
./img-resize img/marching/astro0.png img-smalls/marching/astro0.png
./img-resize img/marching/astro1.png img-smalls/marching/astro1.png
./img-resize img/marching/astro2.png img-smalls/marching/astro2.png
./img-resize img/marching/march1.png img-smalls/marching/march1.png
./img-resize img/marching/marching001.png img-smalls/marching/marching001.png
./img-resize img/marching/marching002.png img-smalls/marching/marching002.png
./img-resize img/marching/marching_sphere.png img-smalls/marching/marching_sphere.png
./img-resize img/marching/mc-branch.png img-smalls/marching/mc-branch.png
./img-resize img/marching/mc-cubenoise.png img-smalls/marching/mc-cubenoise.png
./img-resize img/marching/mc-noise-a.png img-smalls/marching/mc-noise-a.png
./img-resize img/marching/mc-noise-d.png img-smalls/marching/mc-noise-d.png
./img-resize img/marching/mc2-col-yc-2.png img-smalls/marching/mc2-col-yc-2.png
./img-resize img/marching/mc2-col-yc.png img-smalls/marching/mc2-col-yc.png
./img-resize img/marching/mc2-col.png img-smalls/marching/mc2-col.png
./img-resize img/marching/mc2-noise-2.png img-smalls/marching/mc2-noise-2.png
./img-resize img/marching/mc2-noise-3.png img-smalls/marching/mc2-noise-3.png
./img-resize img/marching/mc_asset_b.png img-smalls/marching/mc_asset_b.png
./img-resize img/marching/mc_sb_01.png img-smalls/marching/mc_sb_01.png
./img-resize img/marching/mc_sb_02.png img-smalls/marching/mc_sb_02.png
./img-resize img/marching/mc_sb_03.png img-smalls/marching/mc_sb_03.png
./img-resize img/marching/mc_smooth_0.png img-smalls/marching/mc_smooth_0.png
./img-resize img/marching/mc_smooth_3.png img-smalls/marching/mc_smooth_3.png
./img-resize img/marching/mc_smooth_5.png img-smalls/marching/mc_smooth_5.png
./img-resize img/marching/mc_smooth_oka.png img-smalls/marching/mc_smooth_oka.png
./img-resize img/marching/splat-n1.png img-smalls/marching/splat-n1.png
./img-resize img/marching/splat-yc-2.png img-smalls/marching/splat-yc-2.png
./img-resize img/marching/splat-yc-3.png img-smalls/marching/splat-yc-3.png
./img-resize img/marching/splat-yc-5.png img-smalls/marching/splat-yc-5.png
./img-resize img/marching/yy.png img-smalls/marching/yy.png
./img-resize img/midpoints/g0002.png img-smalls/midpoints/g0002.png
./img-resize img/midpoints/g0004a.png img-smalls/midpoints/g0004a.png
./img-resize img/midpoints/g0004b.png img-smalls/midpoints/g0004b.png
./img-resize img/midpoints/g0005.png img-smalls/midpoints/g0005.png
./img-resize img/midpoints/g0006.png img-smalls/midpoints/g0006.png
./img-resize img/midpoints/g0007.png img-smalls/midpoints/g0007.png
./img-resize img/spiro3/blend_imp_spiro3.png img-smalls/spiro3/blend_imp_spiro3.png
./img-resize img/spiro3/sp3_4.png img-smalls/spiro3/sp3_4.png
./img-resize img/spiro3/sp3_4b.png img-smalls/spiro3/sp3_4b.png
./img-resize img/spiro3/sp3_gear.png img-smalls/spiro3/sp3_gear.png
./img-resize img/spiro3/sp3_gear_03a.png img-smalls/spiro3/sp3_gear_03a.png
./img-resize img/spiro3/sp3_gear_03b.png img-smalls/spiro3/sp3_gear_03b.png
./img-resize img/spiro3/sp3_gear_04.png img-smalls/spiro3/sp3_gear_04.png
./img-resize img/spiro3/sp_n_3.png img-smalls/spiro3/sp_n_3.png
./img-resize img/spiro3/spiro3_005.png img-smalls/spiro3/spiro3_005.png
./img-resize img/spiro3/spiro3_006.png img-smalls/spiro3/spiro3_006.png
./img-resize img/spiro3/spiro3_007.png img-smalls/spiro3/spiro3_007.png
./img-resize img/spiro3/spiro3_008.png img-smalls/spiro3/spiro3_008.png
./img-resize img/spiro3/spiro3_x.png img-smalls/spiro3/spiro3_x.png
./img-resize img/spiro3/spiro3_y.png img-smalls/spiro3/spiro3_y.png
./img-resize img/sphere4d/000.gif img-smalls/sphere4d/000.gif
./img-resize img/sphere4d/b04.png img-smalls/sphere4d/b04.png
./img-resize img/sphere4d/b05.png img-smalls/sphere4d/b05.png
./img-resize img/sphere4d/b06.png img-smalls/sphere4d/b06.png
./img-resize img/sphere4d/c01.png img-smalls/sphere4d/c01.png
./img-resize img/sphere4d/c02.png img-smalls/sphere4d/c02.png
./img-resize img/sphere4d/c03.png img-smalls/sphere4d/c03.png
./img-resize img/sphere4d/c04.png img-smalls/sphere4d/c04.png
./img-resize img/sphere4d/c05.png img-smalls/sphere4d/c05.png
./img-resize img/sphere4d/c06.png img-smalls/sphere4d/c06.png
./img-resize img/sphere4d/c07.png img-smalls/sphere4d/c07.png
./img-resize img/sphere4d/c08.png img-smalls/sphere4d/c08.png
./img-resize img/sphere4d/c09.png img-smalls/sphere4d/c09.png
./img-resize img/sphere4d/c10.png img-smalls/sphere4d/c10.png
./img-resize img/sphere4d/c11.png img-smalls/sphere4d/c11.png
./img-resize img/sphere4d/c12.png img-smalls/sphere4d/c12.png
./img-resize img/sphere4d/c14.png img-smalls/sphere4d/c14.png
./img-resize img/sphere4d/c16.png img-smalls/sphere4d/c16.png
./img-resize img/sphere4d/c17.png img-smalls/sphere4d/c17.png
./img-resize img/sphere4d/c18.png img-smalls/sphere4d/c18.png
./img-resize img/sphere4d/s4.png img-smalls/sphere4d/s4.png
./img-resize img/sphere4d/s4_002.png img-smalls/sphere4d/s4_002.png
./img-resize img/sphere4d/s4_2.png img-smalls/sphere4d/s4_2.png
./img-resize img/sphere4d/sph4_new.png img-smalls/sphere4d/sph4_new.png
./img-resize img/sphere4d/sph4_new_min.png img-smalls/sphere4d/sph4_new_min.png
./img-resize img/parametric/Screenshot-2023-05-27.png img-smalls/parametric/Screenshot-2023-05-27.png
./img-resize img/parametric/clifford_inside.png img-smalls/parametric/clifford_inside.png
./img-resize img/parametric/p005.png img-smalls/parametric/p005.png
./img-resize img/parametric/p006.png img-smalls/parametric/p006.png
./img-resize img/parametric/par_txt001.png img-smalls/parametric/par_txt001.png
./img-resize img/parametric/par_txt001b.png img-smalls/parametric/par_txt001b.png
./img-resize img/parametric/par_txt002.png img-smalls/parametric/par_txt002.png
./img-resize img/parametric/par_txt003.png img-smalls/parametric/par_txt003.png
./img-resize img/parametric/par_txt004.png img-smalls/parametric/par_txt004.png
./img-resize img/parametric/par_txt004b.png img-smalls/parametric/par_txt004b.png
./img-resize img/parametric/parametric0d.png img-smalls/parametric/parametric0d.png
./img-resize img/parametric/parametric_001.png img-smalls/parametric/parametric_001.png
./img-resize img/parametric/parametric_001_p.png img-smalls/parametric/parametric_001_p.png
./img-resize img/parametric/parametric_002.png img-smalls/parametric/parametric_002.png
./img-resize img/parametric/parametric_002_p.png img-smalls/parametric/parametric_002_p.png
./img-resize img/parametric/parametric_003.png img-smalls/parametric/parametric_003.png
./img-resize img/parametric/parametric_003_p.png img-smalls/parametric/parametric_003_p.png
./img-resize img/parametric/parheh.png img-smalls/parametric/parheh.png
./img-resize img/parametric/parheh2.png img-smalls/parametric/parheh2.png
./img-resize img/parametric/partree_b.png img-smalls/parametric/partree_b.png
./img-resize img/times/t_435_61431.png img-smalls/times/t_435_61431.png
./img-resize img/times/t_4_10082.png img-smalls/times/t_4_10082.png
./img-resize img/times/t_68_99989.png img-smalls/times/t_68_99989.png
./img-resize img/times/t_69_99994.png img-smalls/times/t_69_99994.png
./img-resize img/times/t_69_99994_b.png img-smalls/times/t_69_99994_b.png
./img-resize img/times/tf_161_800.png img-smalls/times/tf_161_800.png
./img-resize img/times/tf_201_800.png img-smalls/times/tf_201_800.png
./img-resize img/times/tf_321_800.png img-smalls/times/tf_321_800.png
./img-resize img/times/tf_381_800.png img-smalls/times/tf_381_800.png
./img-resize img/times/tf_425_5041.png img-smalls/times/tf_425_5041.png
./img-resize img/times/tf_446_801.png img-smalls/times/tf_446_801.png
./img-resize img/times/times_02_bw.png img-smalls/times/times_02_bw.png
./img-resize img/times/times_3122_5041.png img-smalls/times/times_3122_5041.png
./img-resize img/times/times_4332_40319.png img-smalls/times/times_4332_40319.png
./img-resize img/times/times_4360_40319.png img-smalls/times/times_4360_40319.png
./img-resize img/times/times_4442_40319.png img-smalls/times/times_4442_40319.png
./img-resize img/times/times_4509_40319.png img-smalls/times/times_4509_40319.png
./img-resize img/times/times_b.png img-smalls/times/times_b.png
./img-resize img/times/times_c.png img-smalls/times/times_c.png
./img-resize img/times/times_circ_bug_1.png img-smalls/times/times_circ_bug_1.png
./img-resize img/times/times_circ_bug_ok.png img-smalls/times/times_circ_bug_ok.png
./img-resize img/times/times_d.png img-smalls/times/times_d.png
./img-resize img/times/times_d_bw.png img-smalls/times/times_d_bw.png
./img-resize img/times/times_x3131_m5009.png img-smalls/times/times_x3131_m5009.png
./img-resize img/times/timesflipped_a.png img-smalls/times/timesflipped_a.png
./img-resize img/times/timesflipped_b.png img-smalls/times/timesflipped_b.png
./img-resize img/times/timesflipped_c.png img-smalls/times/timesflipped_c.png
./img-resize img/times/timesflipped_d.png img-smalls/times/timesflipped_d.png
./img-resize img/times/timesflipped_e.png img-smalls/times/timesflipped_e.png
./img-resize img/times/timesflipped_f.png img-smalls/times/timesflipped_f.png
./img-resize img/times/timesflipped_g.png img-smalls/times/timesflipped_g.png
./img-resize img/times/timesflipped_h.png img-smalls/times/timesflipped_h.png
./img-resize img/times/timesflipped_i.png img-smalls/times/timesflipped_i.png
./img-resize img/times/timesflipped_j.png img-smalls/times/timesflipped_j.png
./img-resize img/times/timesflipped_k.png img-smalls/times/timesflipped_k.png
./img-resize img/times/timesflipped_l.png img-smalls/times/timesflipped_l.png
./img-resize img/voronoi/001.png img-smalls/voronoi/001.png
./img-resize img/voronoi/a001.png img-smalls/voronoi/a001.png
./img-resize img/voronoi/a002.png img-smalls/voronoi/a002.png
./img-resize img/voronoi/a003.png img-smalls/voronoi/a003.png
./img-resize img/voronoi/a04.png img-smalls/voronoi/a04.png
./img-resize img/voronoi/a07.png img-smalls/voronoi/a07.png
./img-resize img/voronoi/a10.png img-smalls/voronoi/a10.png
./img-resize img/voronoi/a12.png img-smalls/voronoi/a12.png
./img-resize img/voronoi/a25_2.png img-smalls/voronoi/a25_2.png
./img-resize img/voronoi/a25_3.png img-smalls/voronoi/a25_3.png
./img-resize img/voronoi/a25_4.png img-smalls/voronoi/a25_4.png
./img-resize img/voronoi/sin01.png img-smalls/voronoi/sin01.png
./img-resize img/voronoi/v01.png img-smalls/voronoi/v01.png
./img-resize img/voronoi/v02.png img-smalls/voronoi/v02.png
./img-resize img/voronoi/v03.png img-smalls/voronoi/v03.png
./img-resize img/voronoi/v04.png img-smalls/voronoi/v04.png
./img-resize img/voronoi/v05.png img-smalls/voronoi/v05.png
./img-resize img/voronoi/v06.png img-smalls/voronoi/v06.png
./img-resize img/voronoi/v07.png img-smalls/voronoi/v07.png
./img-resize img/voronoi/v08.png img-smalls/voronoi/v08.png
./img-resize img/voronoi/v09.png img-smalls/voronoi/v09.png
./img-resize img/voronoi/v10.png img-smalls/voronoi/v10.png
./img-resize img/voronoi/v11.png img-smalls/voronoi/v11.png
./img-resize img/voronoi/v20.png img-smalls/voronoi/v20.png
./img-resize img/voronoi/v21.png img-smalls/voronoi/v21.png
./img-resize img/voronoi/v22.png img-smalls/voronoi/v22.png
./img-resize img/voronoi/v23.png img-smalls/voronoi/v23.png
./img-resize img/voronoi/v24.png img-smalls/voronoi/v24.png
./img-resize img/voronoi/v25.png img-smalls/voronoi/v25.png
./img-resize img/voronoi/v26.png img-smalls/voronoi/v26.png
./img-resize img/voronoi/verr01.png img-smalls/voronoi/verr01.png
./img-resize img/voronoi/vx.png img-smalls/voronoi/vx.png
./img-resize img/voronoi/vx1.png img-smalls/voronoi/vx1.png
./img-resize img/voronoi/vx2.png img-smalls/voronoi/vx2.png
./img-resize img/bugs/bugs01.png img-smalls/bugs/bugs01.png
./img-resize img/bugs/bugs02.png img-smalls/bugs/bugs02.png
./img-resize img/bugs/bugs_-1.png img-smalls/bugs/bugs_-1.png
./img-resize img/bugs/bugs_2.01.png img-smalls/bugs/bugs_2.01.png
./img-resize img/bugs/bugs_2.5.png img-smalls/bugs/bugs_2.5.png
./img-resize img/bugs/bugs_2.5_b.png img-smalls/bugs/bugs_2.5_b.png
./img-resize img/bugs/bugs_sraff.png img-smalls/bugs/bugs_sraff.png
./img-resize img/bugs/bugs_toomuch_2.png img-smalls/bugs/bugs_toomuch_2.png
./img-resize img/bugs/bugs_toomuch_3.png img-smalls/bugs/bugs_toomuch_3.png
./img-resize img/bugs/bugs_toomuch_4.png img-smalls/bugs/bugs_toomuch_4.png
./img-resize img/bugs/bugs_x.png img-smalls/bugs/bugs_x.png
./img-resize img/pascal/g01.png img-smalls/pascal/g01.png
./img-resize img/pascal/g02.png img-smalls/pascal/g02.png
./img-resize img/pascal/g11.png img-smalls/pascal/g11.png
./img-resize img/pascal/g14.png img-smalls/pascal/g14.png
./img-resize img/pascal/g15.png img-smalls/pascal/g15.png
./img-resize img/pascal/g16.png img-smalls/pascal/g16.png
./img-resize img/pascal/g17.png img-smalls/pascal/g17.png
./img-resize img/pascal/p000.png img-smalls/pascal/p000.png
./img-resize img/pascal/p001.png img-smalls/pascal/p001.png
./img-resize img/pascal/p001_err.png img-smalls/pascal/p001_err.png
./img-resize img/pascal/pascal-1.5-2---11-a.png img-smalls/pascal/pascal-1.5-2---11-a.png
./img-resize img/plane_tr/b.png img-smalls/plane_tr/b.png
./img-resize img/plane_tr/bb.png img-smalls/plane_tr/bb.png
./img-resize img/plane_tr/n_2.png img-smalls/plane_tr/n_2.png
./img-resize img/plane_tr/n_4.png img-smalls/plane_tr/n_4.png
./img-resize img/plane_tr/n_5.png img-smalls/plane_tr/n_5.png
./img-resize img/plane_tr/plt_aanqopx_000.png img-smalls/plane_tr/plt_aanqopx_000.png
./img-resize img/plane_tr/plt_caegchb_000.png img-smalls/plane_tr/plt_caegchb_000.png
./img-resize img/plane_tr/plt_eokfyew_000.png img-smalls/plane_tr/plt_eokfyew_000.png
./img-resize img/plane_tr/plt_hlhsjpu_000.png img-smalls/plane_tr/plt_hlhsjpu_000.png
./img-resize img/plane_tr/plt_ikxnyti_000.png img-smalls/plane_tr/plt_ikxnyti_000.png
./img-resize img/plane_tr/plt_kotybek_000.png img-smalls/plane_tr/plt_kotybek_000.png
./img-resize img/plane_tr/plt_kotybek_001.png img-smalls/plane_tr/plt_kotybek_001.png
./img-resize img/plane_tr/plt_mlroynx_000.png img-smalls/plane_tr/plt_mlroynx_000.png
./img-resize img/plane_tr/plt_mlroynx_001.png img-smalls/plane_tr/plt_mlroynx_001.png
./img-resize img/plane_tr/plt_mlroynx_002.png img-smalls/plane_tr/plt_mlroynx_002.png
./img-resize img/plane_tr/plt_ouqvrra_000.png img-smalls/plane_tr/plt_ouqvrra_000.png
./img-resize img/plane_tr/plt_rtqcqxs_000.png img-smalls/plane_tr/plt_rtqcqxs_000.png
./img-resize img/plane_tr/plt_rweadmn_000.png img-smalls/plane_tr/plt_rweadmn_000.png
./img-resize img/plane_tr/plt_sbrknki_000.png img-smalls/plane_tr/plt_sbrknki_000.png
./img-resize img/plane_tr/plt_vzbyfhl_000.png img-smalls/plane_tr/plt_vzbyfhl_000.png
./img-resize img/plane_tr/plt_ygsfnsb_000.png img-smalls/plane_tr/plt_ygsfnsb_000.png
./img-resize img/plane_tr/plt_yqboktm_000.png img-smalls/plane_tr/plt_yqboktm_000.png
./img-resize img/plane_tr/plt_yqboktm_001.png img-smalls/plane_tr/plt_yqboktm_001.png
./img-resize img/plane_tr/plt_zjaerut_001.png img-smalls/plane_tr/plt_zjaerut_001.png
./img-resize img/lorenz/l-langford-1.png img-smalls/lorenz/l-langford-1.png
./img-resize img/lorenz/l-thomas-2.png img-smalls/lorenz/l-thomas-2.png
./img-resize img/lorenz/l-thomas.png img-smalls/lorenz/l-thomas.png
./img-resize img/lorenz/lorenz-cos-sin-a.png img-smalls/lorenz/lorenz-cos-sin-a.png
./img-resize img/lorenz/lorenz-cos-sin-b.png img-smalls/lorenz/lorenz-cos-sin-b.png
./img-resize img/lorenz/lorenz-dadras-a.png img-smalls/lorenz/lorenz-dadras-a.png
./img-resize img/lorenz/lorenz-dadras-b.png img-smalls/lorenz/lorenz-dadras-b.png
./img-resize img/lorenz/lorenz-update.png img-smalls/lorenz/lorenz-update.png
./img-resize img/dandelion/d0.png img-smalls/dandelion/d0.png
./img-resize img/dandelion/d1.png img-smalls/dandelion/d1.png
./img-resize img/dandelion/d2.png img-smalls/dandelion/d2.png
./img-resize img/dandelion/dand-ball.png img-smalls/dandelion/dand-ball.png
./img-resize img/chaosg/cg-x-00.png img-smalls/chaosg/cg-x-00.png
./img-resize img/chaosg/cg-x-01.png img-smalls/chaosg/cg-x-01.png
./img-resize img/chaosg/cg-x-02.png img-smalls/chaosg/cg-x-02.png
./img-resize img/chaosg/cg-x-03.png img-smalls/chaosg/cg-x-03.png
./img-resize img/chaosg/cg-x-04.png img-smalls/chaosg/cg-x-04.png
./img-resize img/chaosg/cg01x.png img-smalls/chaosg/cg01x.png
./img-resize img/chaosg/cg04.png img-smalls/chaosg/cg04.png
./img-resize img/chaosg/cg_rnddiv01.png img-smalls/chaosg/cg_rnddiv01.png
./img-resize img/chaosg/cg_rnddiv03.png img-smalls/chaosg/cg_rnddiv03.png
./img-resize img/chaosg/cg_rnddiv04.png img-smalls/chaosg/cg_rnddiv04.png
./img-resize img/chaosg/chaosgame5a.png img-smalls/chaosg/chaosgame5a.png
./img-resize img/chaosg/chaosgame6a.png img-smalls/chaosg/chaosgame6a.png
./img-resize img/cycloid/cyc_bdatzrd_000.png img-smalls/cycloid/cyc_bdatzrd_000.png
./img-resize img/cycloid/cyc_bdatzrd_001.png img-smalls/cycloid/cyc_bdatzrd_001.png
./img-resize img/cycloid/cyc_bdatzrd_002.png img-smalls/cycloid/cyc_bdatzrd_002.png
./img-resize img/cycloid/cyc_bdatzrd_004.png img-smalls/cycloid/cyc_bdatzrd_004.png
./img-resize img/cycloid/cyc_grtkwcd_000.png img-smalls/cycloid/cyc_grtkwcd_000.png
./img-resize img/cycloid/cyc_xpfwiyl_000.png img-smalls/cycloid/cyc_xpfwiyl_000.png
./img-resize img/cycloid/cyc_yywargu_000.png img-smalls/cycloid/cyc_yywargu_000.png
./img-resize img/cycloid/cycloid_swp.png img-smalls/cycloid/cycloid_swp.png
./img-resize img/cycloid/orb_kvplgdt_000.png img-smalls/cycloid/orb_kvplgdt_000.png
./img-resize img/cycloid/orb_wtzteqe_000.png img-smalls/cycloid/orb_wtzteqe_000.png
./img-resize img/cycloid/orb_wtzteqe_001.png img-smalls/cycloid/orb_wtzteqe_001.png
./img-resize img/cycloid/orb_wtzteqe_002.png img-smalls/cycloid/orb_wtzteqe_002.png
./img-resize img/cycloid/orb_wtzteqe_003.png img-smalls/cycloid/orb_wtzteqe_003.png
./img-resize img/cycloid/orb_wtzteqe_004.png img-smalls/cycloid/orb_wtzteqe_004.png
./img-resize img/cycloid/orb_wtzz.png img-smalls/cycloid/orb_wtzz.png
./img-resize img/spiral/spiral_20.5_290.55_3.png img-smalls/spiral/spiral_20.5_290.55_3.png
./img-resize img/spiral/spiral_20.5_290.55_4.png img-smalls/spiral/spiral_20.5_290.55_4.png
./img-resize img/spiral/spiral_20.5_290.5_1.png img-smalls/spiral/spiral_20.5_290.5_1.png
./img-resize img/spiral/spiral_20.77_290.9_1.png img-smalls/spiral/spiral_20.77_290.9_1.png
./img-resize img/spiral/spiral_20_290__17_a.png img-smalls/spiral/spiral_20_290__17_a.png
./img-resize img/spiral/spiral_45_210_a.png img-smalls/spiral/spiral_45_210_a.png
./img-resize img/spiral/spiral_45_210_b.png img-smalls/spiral/spiral_45_210_b.png
./img-resize img/tri/circ-plt_osyabri_000.png img-smalls/tri/circ-plt_osyabri_000.png
./img-resize img/tri/circ-plt_rrevgis_000.png img-smalls/tri/circ-plt_rrevgis_000.png
./img-resize img/tri/circ-plt_ttbaafp_000.png img-smalls/tri/circ-plt_ttbaafp_000.png
./img-resize img/tri/del_hhmicwp_000.png img-smalls/tri/del_hhmicwp_000.png
./img-resize img/tri/plt_hxqyyxq_000.png img-smalls/tri/plt_hxqyyxq_000.png
./img-resize img/tri/plt_mrdomxg_000.png img-smalls/tri/plt_mrdomxg_000.png
./img-resize img/tri/plt_sgdxhxd_000.png img-smalls/tri/plt_sgdxhxd_000.png
./img-resize img/trochoid/trochoid.gif img-smalls/trochoid/trochoid.gif
./img-resize img/grid/tt_arwpglw_000.png img-smalls/grid/tt_arwpglw_000.png
./img-resize img/grid/tt_bvwxxkk_000.png img-smalls/grid/tt_bvwxxkk_000.png
./img-resize img/grid/tt_heggapy_000.png img-smalls/grid/tt_heggapy_000.png
./img-resize img/grid/tt_hhlxbor_000.png img-smalls/grid/tt_hhlxbor_000.png
./img-resize img/grid/tt_ioskrup_000.png img-smalls/grid/tt_ioskrup_000.png
./img-resize img/grid/tt_ioskrup_001.png img-smalls/grid/tt_ioskrup_001.png
./img-resize img/grid/tt_ioznacc_000.png img-smalls/grid/tt_ioznacc_000.png
./img-resize img/grid/tt_ioznacc_001.png img-smalls/grid/tt_ioznacc_001.png
./img-resize img/grid/tt_jluyzzr_000.png img-smalls/grid/tt_jluyzzr_000.png
./img-resize img/grid/tt_jluyzzr_001.png img-smalls/grid/tt_jluyzzr_001.png
./img-resize img/grid/tt_jluyzzr_002.png img-smalls/grid/tt_jluyzzr_002.png
./img-resize img/grid/tt_jluyzzr_003.png img-smalls/grid/tt_jluyzzr_003.png
./img-resize img/grid/tt_jluyzzr_004.png img-smalls/grid/tt_jluyzzr_004.png
./img-resize img/grid/tt_jluyzzr_005.png img-smalls/grid/tt_jluyzzr_005.png
./img-resize img/grid/tt_jrhobyd_001.png img-smalls/grid/tt_jrhobyd_001.png
./img-resize img/grid/tt_jwxokov_000.png img-smalls/grid/tt_jwxokov_000.png
./img-resize img/grid/tt_ljswgua_000.png img-smalls/grid/tt_ljswgua_000.png
./img-resize img/grid/tt_mtfwhqu_000.png img-smalls/grid/tt_mtfwhqu_000.png
./img-resize img/grid/tt_njszzwx_000.png img-smalls/grid/tt_njszzwx_000.png
./img-resize img/grid/tt_nrpwqan_000.png img-smalls/grid/tt_nrpwqan_000.png
./img-resize img/grid/tt_oykffub_000.png img-smalls/grid/tt_oykffub_000.png
./img-resize img/grid/tt_sagfirr_000.png img-smalls/grid/tt_sagfirr_000.png
./img-resize img/grid/tt_tnlwlln_000.png img-smalls/grid/tt_tnlwlln_000.png
./img-resize img/grid/tt_uusbaeq_000.png img-smalls/grid/tt_uusbaeq_000.png
./img-resize img/grid/tt_vcxbjcq_000.png img-smalls/grid/tt_vcxbjcq_000.png
./img-resize img/grid/tt_yfegbqp_000.png img-smalls/grid/tt_yfegbqp_000.png
./img-resize img/terrain/cx2_tt_zqpzlny_001.png img-smalls/terrain/cx2_tt_zqpzlny_001.png
./img-resize img/terrain/gli1.png img-smalls/terrain/gli1.png
./img-resize img/terrain/gsim_egxqqsm_000.png img-smalls/terrain/gsim_egxqqsm_000.png
./img-resize img/terrain/gsim_jppxh_002.png img-smalls/terrain/gsim_jppxh_002.png
./img-resize img/terrain/gsim_lgvivru_000.png img-smalls/terrain/gsim_lgvivru_000.png
./img-resize img/terrain/gsim_mffakwv_000.png img-smalls/terrain/gsim_mffakwv_000.png
./img-resize img/terrain/gsim_mlftkem_001.png img-smalls/terrain/gsim_mlftkem_001.png
./img-resize img/terrain/gsim_qxupbuv_000.png img-smalls/terrain/gsim_qxupbuv_000.png
./img-resize img/terrain/gsim_tqobudo_000.png img-smalls/terrain/gsim_tqobudo_000.png
./img-resize img/terrain/gstt_meteorit_02.png img-smalls/terrain/gstt_meteorit_02.png
./img-resize img/terrain/h2.png img-smalls/terrain/h2.png
./img-resize img/terrain/h3.png img-smalls/terrain/h3.png
./img-resize img/terrain/h4.png img-smalls/terrain/h4.png
./img-resize img/terrain/hb0.png img-smalls/terrain/hb0.png
./img-resize img/terrain/hb1.png img-smalls/terrain/hb1.png
./img-resize img/terrain/hb10.png img-smalls/terrain/hb10.png
./img-resize img/terrain/hb2.png img-smalls/terrain/hb2.png
./img-resize img/terrain/hb3.png img-smalls/terrain/hb3.png
./img-resize img/terrain/hb9.png img-smalls/terrain/hb9.png
./img-resize img/terrain/nw_daftkai_000.png img-smalls/terrain/nw_daftkai_000.png
./img-resize img/terrain/nw_daftkai_001.png img-smalls/terrain/nw_daftkai_001.png
./img-resize img/terrain/nw_daftkai_002.png img-smalls/terrain/nw_daftkai_002.png
./img-resize img/terrain/nw_daftkai_003.png img-smalls/terrain/nw_daftkai_003.png
./img-resize img/terrain/nw_euolyqj_000.png img-smalls/terrain/nw_euolyqj_000.png
./img-resize img/terrain/nw_ogmaqfr_000.png img-smalls/terrain/nw_ogmaqfr_000.png
./img-resize img/terrain/nw_ylcvwnm_000.png img-smalls/terrain/nw_ylcvwnm_000.png
./img-resize img/terrain/nw_yvxaymi_000.png img-smalls/terrain/nw_yvxaymi_000.png
./img-resize img/terrain/nw_zwpritw_000.png img-smalls/terrain/nw_zwpritw_000.png
./img-resize img/terrain/sea0.png img-smalls/terrain/sea0.png
./img-resize img/terrain/sea1.png img-smalls/terrain/sea1.png
./img-resize img/terrain/sea2.png img-smalls/terrain/sea2.png
./img-resize img/terrain/sea3.png img-smalls/terrain/sea3.png
./img-resize img/terrain/sea4.png img-smalls/terrain/sea4.png
./img-resize img/terrain/sea5.png img-smalls/terrain/sea5.png
./img-resize img/terrain/sea6.png img-smalls/terrain/sea6.png
./img-resize img/terrain/sea9.png img-smalls/terrain/sea9.png
./img-resize img/terrain/smr1.png img-smalls/terrain/smr1.png
./img-resize img/terrain/surf0.png img-smalls/terrain/surf0.png
./img-resize img/terrain/surf1.png img-smalls/terrain/surf1.png
./img-resize img/terrain/talus0.png img-smalls/terrain/talus0.png
./img-resize img/terrain/tt_bfozsmv_000.png img-smalls/terrain/tt_bfozsmv_000.png
./img-resize img/terrain/tt_daedreh_000.png img-smalls/terrain/tt_daedreh_000.png
./img-resize img/terrain/tt_daedreh_001.png img-smalls/terrain/tt_daedreh_001.png
./img-resize img/terrain/tt_gevxbyz_000.png img-smalls/terrain/tt_gevxbyz_000.png
./img-resize img/terrain/tt_ggkspyd_000.png img-smalls/terrain/tt_ggkspyd_000.png
./img-resize img/terrain/tt_giiaagc_000.png img-smalls/terrain/tt_giiaagc_000.png
./img-resize img/terrain/tt_gpwvtgm_000.png img-smalls/terrain/tt_gpwvtgm_000.png
./img-resize img/terrain/tt_hfybjcb_000.png img-smalls/terrain/tt_hfybjcb_000.png
./img-resize img/terrain/tt_ivkncmo_000.png img-smalls/terrain/tt_ivkncmo_000.png
./img-resize img/terrain/tt_iwzzqxs_000.png img-smalls/terrain/tt_iwzzqxs_000.png
./img-resize img/terrain/tt_ljeupsz_000.png img-smalls/terrain/tt_ljeupsz_000.png
./img-resize img/terrain/tt_oiglumh_000.png img-smalls/terrain/tt_oiglumh_000.png
./img-resize img/terrain/tt_pynwxxh_000.png img-smalls/terrain/tt_pynwxxh_000.png
./img-resize img/terrain/tt_wfyghyh_000.png img-smalls/terrain/tt_wfyghyh_000.png
./img-resize img/terrain/tt_wovshkc_000.png img-smalls/terrain/tt_wovshkc_000.png
./img-resize img/terrain/tt_xvxeznl_000.png img-smalls/terrain/tt_xvxeznl_000.png
./img-resize img/terrain/tt_znnlmzf_000.png img-smalls/terrain/tt_znnlmzf_000.png
./img-resize img/planets/cliffs_ceouimn_000.png img-smalls/planets/cliffs_ceouimn_000.png
./img-resize img/planets/cliffs_dlkdyqi_000.png img-smalls/planets/cliffs_dlkdyqi_000.png
./img-resize img/planets/cliffs_dlkdyqi_001.png img-smalls/planets/cliffs_dlkdyqi_001.png
./img-resize img/planets/cliffs_hycvxid_000.png img-smalls/planets/cliffs_hycvxid_000.png
./img-resize img/planets/cliffs_jwqmvyd_000.png img-smalls/planets/cliffs_jwqmvyd_000.png
./img-resize img/planets/cliffs_jwqmvyd_001.png img-smalls/planets/cliffs_jwqmvyd_001.png
./img-resize img/planets/cliffs_jwqmvyd_003.png img-smalls/planets/cliffs_jwqmvyd_003.png
./img-resize img/planets/cliffs_njmxmcl_000.png img-smalls/planets/cliffs_njmxmcl_000.png
./img-resize img/planets/cliffs_njmxmcl_001.png img-smalls/planets/cliffs_njmxmcl_001.png
./img-resize img/planets/cliffs_solaqra_001.png img-smalls/planets/cliffs_solaqra_001.png
./img-resize img/planets/cliffs_sxnmqjy_000.png img-smalls/planets/cliffs_sxnmqjy_000.png
./img-resize img/planets/cliffs_ultvaix_000.png img-smalls/planets/cliffs_ultvaix_000.png
./img-resize img/planets/cliffs_yvmavul_001.png img-smalls/planets/cliffs_yvmavul_001.png
./img-resize img/planets/cliffs_zznjqpr_000.png img-smalls/planets/cliffs_zznjqpr_000.png
./img-resize img/planets/cliffs_zznjqpr_001.png img-smalls/planets/cliffs_zznjqpr_001.png
./img-resize img/planets/nw_ffedecx_000.png img-smalls/planets/nw_ffedecx_000.png
./img-resize img/planets/nw_ffedecx_001.png img-smalls/planets/nw_ffedecx_001.png
./img-resize img/planets/nw_fwqvwok_000.png img-smalls/planets/nw_fwqvwok_000.png
./img-resize img/planets/nw_jtodptk_001.png img-smalls/planets/nw_jtodptk_001.png
./img-resize img/planets/nw_oeqsreg_000.png img-smalls/planets/nw_oeqsreg_000.png
./img-resize img/planets/nw_ofaecwu_000.png img-smalls/planets/nw_ofaecwu_000.png
./img-resize img/planets/nw_ofaecwu_001.png img-smalls/planets/nw_ofaecwu_001.png
./img-resize img/planets/nw_uugwarl_000.png img-smalls/planets/nw_uugwarl_000.png
./img-resize img/planets/nw_yhhbozf_000.png img-smalls/planets/nw_yhhbozf_000.png
./img-resize img/planets/planets_fhrdrzp_000.png img-smalls/planets/planets_fhrdrzp_000.png
./img-resize img/planets/planets_tlstzgu_000.png img-smalls/planets/planets_tlstzgu_000.png
./img-resize img/planets/planets_tlstzgu_002.png img-smalls/planets/planets_tlstzgu_002.png
./img-resize img/newworld/nw-00.png img-smalls/newworld/nw-00.png
./img-resize img/newworld/nw-01.png img-smalls/newworld/nw-01.png
./img-resize img/newworld/nw-02-a.png img-smalls/newworld/nw-02-a.png
./img-resize img/newworld/nw-02-b.png img-smalls/newworld/nw-02-b.png
./img-resize img/newworld/nw-02-c.png img-smalls/newworld/nw-02-c.png
./img-resize img/newworld/nw-browser.png img-smalls/newworld/nw-browser.png
./img-resize img/newworld/nw-fish-01.png img-smalls/newworld/nw-fish-01.png
./img-resize img/newworld/nw-point-fish-02.png img-smalls/newworld/nw-point-fish-02.png
./img-resize img/newworld/nw-point-fish-03.png img-smalls/newworld/nw-point-fish-03.png
./img-resize img/newworld/nw_afkwlwt_000.png img-smalls/newworld/nw_afkwlwt_000.png
./img-resize img/newworld/nw_fghvitl_000.png img-smalls/newworld/nw_fghvitl_000.png
./img-resize img/newworld/nw_fghvitl_002.png img-smalls/newworld/nw_fghvitl_002.png
./img-resize img/newworld/nw_fghvitl_003.png img-smalls/newworld/nw_fghvitl_003.png
./img-resize img/newworld/nw_green.png img-smalls/newworld/nw_green.png
./img-resize img/newworld/nw_mbijbjk_001.png img-smalls/newworld/nw_mbijbjk_001.png
./img-resize img/newworld/nw_qrxltmp_000.png img-smalls/newworld/nw_qrxltmp_000.png
./img-resize img/newworld/nw_strmdcc_000.png img-smalls/newworld/nw_strmdcc_000.png
./img-resize img/newworld/nw_tvomayq_000.png img-smalls/newworld/nw_tvomayq_000.png
./img-resize img/newworld/nw_vzabmwj_000.png img-smalls/newworld/nw_vzabmwj_000.png
./img-resize img/newworld/nwg01_a.png img-smalls/newworld/nwg01_a.png
./img-resize img/newworld/nwg01_b.png img-smalls/newworld/nwg01_b.png
./img-resize img/newworld/nwg02_c.png img-smalls/newworld/nwg02_c.png
./img-resize img/newworld/nwg02_d.png img-smalls/newworld/nwg02_d.png
./img-resize img/newworld/nwg02_dd.png img-smalls/newworld/nwg02_dd.png
./img-resize img/newworld/nwg02_e.png img-smalls/newworld/nwg02_e.png
./img-resize img/newworld/nwg02_g.png img-smalls/newworld/nwg02_g.png
./img-resize img/newworld/nwg02_i.png img-smalls/newworld/nwg02_i.png
./img-resize img/newworld/nwg02_j.png img-smalls/newworld/nwg02_j.png
./img-resize img/newworld/nwg02_k.png img-smalls/newworld/nwg02_k.png
./img-resize img/newworld/nwg02_l.png img-smalls/newworld/nwg02_l.png
./img-resize img/newworld/nwg02_m.png img-smalls/newworld/nwg02_m.png
./img-resize img/newworld/nwg02_r.png img-smalls/newworld/nwg02_r.png
./img-resize img/newworld/nwg02_s.png img-smalls/newworld/nwg02_s.png
